### ISSUE TITLE
Identify which factors we will choose

### ISSUE THREAD

**Issue by Makiato1999** [Makiato1999/COMP4710-Group13#4]
To do:
- [x] COVID-19 cases
- [x] COVID-19 total_tests
- [x] people_fully_vaccinated
- [x] COVID-19 total_deaths
- [x] reproduction_rate
- [x] Inflation rate: CPI (Consumer Price Index)
- [x] Unemployment rate
- [x] Canada COVID-19 cases
- [x] Canada Inflation rate: CPI
- [x] Canada Unemployment rate
- [x] reproduction_rate
- [ ] GDP
- [ ] Hospital patients
- [ ] Interest Rate
- [ ] Medical resources
- [ ] Vaccine doses?
- [ ] Confirmed deaths?

Monthly data which we have done:
- [x] Canada_UnemploymentRates_Monthly
- [x] China_NewCovidCases_Monthly
- [x] France_InflationCPl_Monthly.csv
- [x] France_NewCovidCases_Monthly
- [x] India_NewCovidCases_Monthly
- [x] Philippiie_InflationCPI_Monthly
- [x] Philippine_NewCovidCases_Monthly
- [x] Philippine_UnemploymentRate_Monthly
- [x] SouthKorea_InflationCPI_Monthly
- [x] SouthKorea_NewCovidCases_Monthly
- [x] SouthKorea_UnemploymentRate_Monthly

Expected time: unlimited

**Comment by Makiato1999** [comment]
France
Unemployment rate: https://ycharts.com/indicators/france_unemployment_rate

**Comment by yunji0387** [comment]
India :
1. [Unemployment rates](https://unemploymentinindia.cmie.com/)

**Comment by ZhijieZheng-UM** [comment]
#7 
China:

1. Inflation rate (2019.1~2022.9): https://ycharts.com/indicators/china_inflation_rate

2. Unemployment rate (2019.1~2022.9): https://ycharts.com/indicators/china_urban_survey_unemployment_rate
https://www.statista.com/statistics/1109881/surveyed-monthly-unemployment-rate-in-china/

**Comment by yunji0387** [comment]
Canada : 
 1. Unemployment rates
    - 2019/1 ~ 2022/9
    - https://data.oecd.org/unemp/unemployment-rate.htm

**Comment by Makiato1999** [comment]
Philippines(#11):
1. COVID cases (2020.1-2022.9): https://github.com/owid/covid-19-data/tree/master/public/data
2. Inflation rate (2019.1-2022.9): https://psa.gov.ph/price-indices/cpi-ir/title/Summary%20Inflation%20Report%20Consumer%20Price%20Index%20%282018%3D100%29%3A%20September%202022
4. Unemployment rate (2019.1-2022.9):https://psa.gov.ph/content/employment-rate-january-2019-estimated-948-percent
5. GDP (2019.Q1-2022.Q1):

**Comment by Makiato1999** [comment]
South Korea(#8): https://github.com/owid/covid-19-data/tree/master/public/data
1. COVID cases (2020.1-2022.9):
2. Inflation rate (2019.1-2022.9): https://www.rateinflation.com/inflation-rate/korea-inflation-rate/
3. Unemployment rate (2019.1-2022.9):https://kostat.go.kr/wnsearchEng/search.jsp?query=Economically+Active+Population+Survey
4. GDP (2019.Q1-2022.Q1):
