### ISSUE TITLE
Collect data: South Korea

### ISSUE THREAD

**Issue by Makiato1999** [Makiato1999/COMP4710-Group13#8]
To do:
- Same as we choose countries, time is between: 2019Q1-2022Q3
- Create a new table to save related data, columns are factors

Expected: 2days

**Comment by Yorifong** [comment]
1. COVID cases (2020.1.24-2022.11.7):
**2. Inflation rate (2019.1-2022.9): https://www.rateinflation.com/inflation-rate/korea-inflation-rate/
3. Unemployment rate (2019.1-2022.7):https://kostat.go.kr/wnsearchEng/search.jsp?query=Economically+Active+Population+Survey**
4. GDP (2019.Q1-2022.Q1):
